services:
  mongo:
    image: mongo:7.0
    container_name: billing-local-mongo
    ports:
      - "27017:27017"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 10s
      timeout: 5s
      retries: 5

  tenant-service:
    build:
      context: ./tenant-service
    container_name: billing-tenant-service
    depends_on:
      mongo:
        condition: service_healthy
    environment:
      TENANT_MONGODB_URI: mongodb://mongo:27017/billing_tenant
    ports:
      - "8081:8081"
    restart: unless-stopped

  usage-service:
    build:
      context: ./usage-service
    container_name: billing-usage-service
    depends_on:
      mongo:
        condition: service_healthy
    environment:
      USAGE_MONGODB_URI: mongodb://mongo:27017/billing_usage
    ports:
      - "8082:8082"
    restart: unless-stopped

  billing-service:
    build:
      context: ./billing-service
    container_name: billing-billing-service
    depends_on:
      mongo:
        condition: service_healthy
    ports:
      - "8083:8083"
    restart: unless-stopped

  invoice-batch-service:
    build:
      context: ./invoice-batch-service
    container_name: billing-invoice-batch-service
    depends_on:
      mongo:
        condition: service_healthy
    environment:
      INVOICE_MONGODB_URI: mongodb://mongo:27017/billing_invoice
      INTEGRATION_PAYMENT_BASE_URL: http://payment-service:8085
      INTEGRATION_SETTLEMENT_BASE_URL: http://settlement-service:8086
    ports:
      - "8084:8084"
    restart: unless-stopped

  payment-service:
    build:
      context: ./payment-service
    container_name: billing-payment-service
    depends_on:
      mongo:
        condition: service_healthy
    environment:
      PAYMENT_MONGODB_URI: mongodb://mongo:27017/billing_payment
    ports:
      - "8085:8085"
    restart: unless-stopped

  settlement-service:
    build:
      context: ./settlement-service
    container_name: billing-settlement-service
    depends_on:
      mongo:
        condition: service_healthy
    environment:
      SETTLEMENT_MONGODB_URI: mongodb://mongo:27017/billing_settlement
    ports:
      - "8086:8086"
    restart: unless-stopped
