global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "tenant-service"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["tenant-service:8081"]

  - job_name: "usage-service"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["usage-service:8082"]

  - job_name: "billing-service"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["billing-service:8083"]

  - job_name: "invoice-batch-service"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["invoice-batch-service:8084"]

  - job_name: "payment-service"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["payment-service:8085"]

  - job_name: "settlement-service"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["settlement-service:8086"]
