apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: billing-platform

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - mongo.yaml
  - tenant-service.yaml
  - usage-service.yaml
  - billing-service.yaml
  - invoice-batch-service.yaml
  - payment-service.yaml
  - settlement-service.yaml
  - hpa.yaml
  - ingress.yaml
