apiVersion: v1
kind: Secret
metadata:
  name: billing-platform-secrets
type: Opaque
stringData:
  PLATFORM_SECURITY_API_KEY_VALUE: "change-me-api-key"
  PLATFORM_SECURITY_BEARER_TOKENS: "change-me-token"
  PLATFORM_SECURITY_BEARER_TOKEN_SCOPES: "change-me-token=tenant:write|usage:write|usage:read|billing:write|invoice:write|invoice:read|invoice:settle|payment:write|settlement:write|settlement:read"
  PLATFORM_SECURITY_BEARER_TOKEN_TENANTS: "change-me-token=*"
